### ISSUE TITLE
Cannot access /admin when running on other port than 80

### ISSUE THREAD

**Issue by mrtolkien** [docker-taiga/taiga#43]
Hello again,

I have managed to get most of the project working on port 8080, but some features like /admin do not work. As the Taiga documentation is pretty laconic, I’m not sure if it’s supposed to be there but the behaviour is definitely weird.

Additionally, emails sending does not work either.

Steps to reproduce:
- Clone the repo
- Change TAIGA_HOST to the machine’s public URL and TAIGA_PORT to 8080
- Change docker-compose.yml to redirect the host’s 8080 port to the proxy’s 80

Result:
- Creating projects and tasks works
- Updating user picture and password works
- /admin and /api return `Not Found - The requested resource was not found on this server.` and not the standard Taiga 404 error
- /media weirdly redirect me to /media on the 80 port of the host
- /events returns `Upgrade Required`
- /test properly shows the Taiga 404 page
- Sending emails to invite new users does not work (despite the UX saying it did)

**Comment by w1ck3dg0ph3r** [comment]
Hi!

> /admin and /api return Not Found - The requested resource was not found on this server. and not the standard Taiga 404 error

IIRC, django admin is sensitive to trailing slash, i.e. you should access `http://taiga.host/admin/`. As for the API - it's `http://taiga.host/api/v1/`, if you want to get the available endpoints .

> /media weirdly redirect me to /media on the 80 port of the host

That's because /media is handled by nginx itself simply for serving files. Maybe we could fix that in nginx config, but I don't see the need for it. The attachments should work properly.

> /events returns Upgrade Required

Events is a websocket service, so that is expected.

> Sending emails to invite new users does not work (despite the UX saying it did)

As I remember, taiga is sending emails asynchronously with the default setup (with celery enabled), so you wouldn't get UI notifications. The problem should be indicated in taiga-back logs or your SMTP server logs. If the email backend is not configured, taiga would just dump the message body to the log, if I'm not mistaken.
